version: '3'

services:
  api:
    build: ./containers/api
    volumes:
      - .:/code
    depends_on:
      - mongo
    ports:
      - 3000:3000
    command: ["/code/run-dev.sh"]

  mongo:
    image: mongo:4.2-bionic
    volumes:
      - data_mongo:/data/db

  minio:
    image: minio/minio
    ports:
      - 3001:9000
    command: ['minio', 'server', '/data']
    volumes:
      - data_minio:/data
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7SPA
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYSPA

volumes:
  data_mongo:
  data_minio:
