services:
  my_command:
    class: App::MyCommand
    kwargs:
      input: '@console_input'
      output: '@console_output'
    tag:
      - command

  # framework extensions
  http_error_handler:
   class: App::ErrorHandler

  # controllers
  home_controller:
    class: App::HomeController
    tag:
      - controller

  oauth_controller:
    class: App::OAuthController
    kwargs:
      auth_service: '@auth_service'
    tag:
      - controller

  user_controller:
    class: App::UserController
    kwargs:
      user_serializer: '@user_serializer'
      user_service: '@user_service'
      user_repository: '@user_repository'
    tag:
      - controller

  product_category_controller:
    class: App::ProductCategoryController
    kwargs:
      serializer: '@product_category_serializer.as(App::Serializer(App::ProductCategory))'
      service: '@product_category_service'
      repository: '@product_category_repository.as(App::CrudRepository(App::ProductCategory))'
      policy: '@product_category_policy.as(App::CrudPolicy(App::ProductCategory))'
      user_repository: '@user_repository'
    tag:
      - controller

  # services
  user_service:
    class: App::UserService
    kwargs:
      user_repository: '@user_repository'
      crypt_service: '@crypt_service'

  auth_service:
    class: App::AuthService
    kwargs:
      user_repository: '@user_repository'
      crypt_service: '@crypt_service'
      app_secret: '%app_secret:String%'

  crypt_service:
    class: App::CryptService

  product_category_service:
    class: App::ProductCategoryService
    kwargs:
      repository: '@product_category_repository.as(App::CrudRepository(App::ProductCategory))'
      validator: '@product_category_validator'

  # repositories
  user_repository:
    class: App::UserRepository
    kwargs:
      connection: '@db_connection'

  product_category_repository:
    class: App::ProductCategoryRepository
    kwargs:
      connection: '@db_connection'

  # serializers
  user_serializer:
    class: App::UserSerializer

  product_category_serializer:
    class: App::ProductCategorySerializer

  # validators
  product_category_validator:
    class: App::ProductCategoryValidator

  # policies
  product_category_policy:
    class: App::ProductCategoryPolicy

  # middlewares
  content_type_middleware:
    class: App::ContentTypeMiddleware
    tag:
      - route_middleware

  auth_middleware:
    class: App::AuthMiddleware
    kwargs:
      auth_service: '@auth_service'
    tag:
      - route_middleware
